
CREATE TABLE IF NOT EXISTS `Achat`.`SITES` (
  `SITEID` VARCHAR(2) NOT NULL,
  `DESCRIPTION` VARCHAR(20) NULL,
  PRIMARY KEY (`SITEID`))
ENGINE = InnoDB


CREATE TABLE IF NOT EXISTS `Achat`.`CATEGORY` (
  `CATEGORY` VARCHAR(4) NOT NULL,
  `DESCRIPTION` VARCHAR(20) NULL,
  PRIMARY KEY (`CATEGORY`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `Achat`.`USERS` (
  `USERID` VARCHAR(4) NOT NULL,
  `DESCRIPTION` VARCHAR(20) NULL,
  `EMAIL` VARCHAR(50) NULL,
  `PASSWORD` VARCHAR(60) NULL,
  `STATUS` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`USERID`))
ENGINE = InnoDB


CREATE TABLE IF NOT EXISTS `Achat`.`PRODUCT` (
  `BARCODE` VARCHAR(16) NOT NULL,
  `DESCRIPTION` VARCHAR(20) NOT NULL,
  `TVA` DECIMAL(10,3) NOT NULL,
  `TVA_TYPE` VARCHAR(1) NOT NULL,
  `STATUS` VARCHAR(1) NOT NULL,
  `CATEGORY` VARCHAR(4) NULL,
  `USERID` VARCHAR(4) NULL,
  PRIMARY KEY (`BARCODE`),
  INDEX `fk_PRODUCT_1_idx` (`CATEGORY` ASC),
  INDEX `fk_PRODUCT_2_idx` (`USERID` ASC),
  CONSTRAINT `fk_PRODUCT_1`
    FOREIGN KEY (`CATEGORY`)
    REFERENCES `Achat`.`CATEGORY` (`CATEGORY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_2`
    FOREIGN KEY (`USERID`)
    REFERENCES `Achat`.`USERS` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB


CREATE TABLE IF NOT EXISTS `Achat`.`SUPPLIER` (
  `SUPPLIERID` VARCHAR(5) NOT NULL,
  `DESCRIPTION` VARCHAR(20) NOT NULL,
  `TEL` VARCHAR(20) NULL,
  `EMAIL` VARCHAR(50) NULL,
  `STATUS` VARCHAR(1) NOT NULL,
  `ADDRESS` VARCHAR(100) NULL,
  `USERID` VARCHAR(4) NULL,
  PRIMARY KEY (`SUPPLIERID`),
  INDEX `fk_SUPPLIER_1_idx` (`USERID` ASC),
  CONSTRAINT `fk_SUPPLIER_1`
    FOREIGN KEY (`USERID`)
    REFERENCES `Achat`.`USERS` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB




CREATE TABLE IF NOT EXISTS `Achat`.`Supplier_Products` (
  `BARCODE` VARCHAR(8) NOT NULL,
  `SUPPLIERID` VARCHAR(5) NOT NULL,
  `USERID` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`BARCODE`, `SUPPLIERID`, `USERID`),
  INDEX `fk_Supplier_Products_2_idx` (`SUPPLIERID` ASC),
  INDEX `fk_Supplier_Products_3_idx` (`USERID` ASC),
  CONSTRAINT `fk_Supplier_Products_1`
    FOREIGN KEY (`BARCODE`)
    REFERENCES `Achat`.`PRODUCT` (`BARCODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supplier_Products_2`
    FOREIGN KEY (`SUPPLIERID`)
    REFERENCES `Achat`.`SUPPLIER` (`SUPPLIERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supplier_Products_3`
    FOREIGN KEY (`USERID`)
    REFERENCES `Achat`.`USERS` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB



CREATE TABLE IF NOT EXISTS `Achat`.`PURCHASES` (
  `DOCID` VARCHAR(14) NOT NULL,
  `SITEID` VARCHAR(2) NOT NULL,
  `TRSDATE` DATE NOT NULL,
  `BARCODE` VARCHAR(8) NOT NULL,
  `SUPPLIERID` VARCHAR(5) NULL,
  `QTY` INT(8) NULL,
  `USERID` VARCHAR(4) NULL,
  PRIMARY KEY (`DOCID`),
  INDEX `fk_PURCHASES_1_idx` (`SITEID` ASC),
  INDEX `fk_PURCHASES_2_idx` (`BARCODE` ASC),
  INDEX `fk_PURCHASES_3_idx` (`SUPPLIERID` ASC),
  INDEX `fk_PURCHASES_4_idx` (`USERID` ASC),
  CONSTRAINT `fk_PURCHASES_1`
    FOREIGN KEY (`SITEID`)
    REFERENCES `Achat`.`SITES` (`SITEID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PURCHASES_2`
    FOREIGN KEY (`BARCODE`)
    REFERENCES `Achat`.`PRODUCT` (`BARCODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PURCHASES_3`
    FOREIGN KEY (`SUPPLIERID`)
    REFERENCES `Achat`.`SUPPLIER` (`SUPPLIERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PURCHASES_4`
    FOREIGN KEY (`USERID`)
    REFERENCES `Achat`.`USERS` (`USERID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB



CREATE TABLE IF NOT EXISTS `Achat`.`RECEPT` (
  `DOCID` VARCHAR(14) NOT NULL,
  `SITEID` VARCHAR(2) NULL,
  `TRSDATE` DATE NULL,
  `RELATED_DOCID` VARCHAR(14) NULL,
  `INVOICE_DISCOUNT` DECIMAL(4,2) NULL,
  PRIMARY KEY (`DOCID`),
  INDEX `fk_RECEPT_1_idx` (`SITEID` ASC),
  INDEX `fk_RECEPT_2_idx` (`RELATED_DOCID` ASC),
  CONSTRAINT `fk_RECEPT_1`
    FOREIGN KEY (`SITEID`)
    REFERENCES `Achat`.`SITES` (`SITEID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECEPT_2`
    FOREIGN KEY (`RELATED_DOCID`)
    REFERENCES `Achat`.`PURCHASES` (`DOCID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB



CREATE TABLE IF NOT EXISTS `Achat`.`Recept_dtl` (
  `DOCID` VARCHAR(14) NULL,
  `BARCODE` VARCHAR(8) NULL,
  `QTY` DECIMAL(11,2) NULL,
  `PURCHASE_PRICE` DECIMAL(10,3) NULL,
  `ITEM_DISCOUNT` DECIMAL(4,2) NULL,
  INDEX `fk_Recept_dtl_1_idx` (`DOCID` ASC),
  INDEX `fk_Recept_dtl_2_idx` (`BARCODE` ASC),
  CONSTRAINT `fk_Recept_dtl_1`
    FOREIGN KEY (`DOCID`)
    REFERENCES `Achat`.`RECEPT` (`DOCID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recept_dtl_2`
    FOREIGN KEY (`BARCODE`)
    REFERENCES `Achat`.`PRODUCT` (`BARCODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB



CREATE TABLE IF NOT EXISTS `Achat`.`STK_PRD` (
  `SITEID` VARCHAR(2) NULL,
  `BARCODE` VARCHAR(8) NULL,
  `QTY` INT(5) NULL,
  `QTY_NOTIFICATION` INT(5) NULL,
  INDEX `fk_STK_PRD_1_idx` (`SITEID` ASC),
  INDEX `fk_STK_PRD_2_idx` (`BARCODE` ASC),
  CONSTRAINT `fk_STK_PRD_1`
    FOREIGN KEY (`SITEID`)
    REFERENCES `Achat`.`SITES` (`SITEID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STK_PRD_2`
    FOREIGN KEY (`BARCODE`)
    REFERENCES `Achat`.`PRODUCT` (`BARCODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB



CREATE TABLE IF NOT EXISTS `Achat`.`STK_TRS` (
  `SITEID` VARCHAR(2) NOT NULL,
  `DOCID` VARCHAR(14) NOT NULL,
  `TRSDATE` DATE NOT NULL,
  `DOCTYPE` VARCHAR(1) NOT NULL,
  `BARCODE` VARCHAR(8) NOT NULL,
  `QTY` INT(5) NOT NULL,
  `RELATED_DOCID` VARCHAR(14) NULL,
  `TVA` DECIMAL(10,3) NULL,
  `TVA_TYPE` VARCHAR(1) NULL,
  `SUPPLIERID` VARCHAR(5) NULL,
  `USERID` VARCHAR(4) NOT NULL,
  `PURCHASE_PRICE` DECIMAL(10,3) NULL)
ENGINE = InnoDB


